In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
# Simple array creation

import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([[1,2],[3,4]])

print(arr1)
print(arr2)

[1 2 3]
[[1 2]
 [3 4]]


In [ ]:
# Core Numpy operations

arr2 = np.zeros((2,2))
arr1 = np.ones((2,3))

print(arr2)
print(arr1)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Array Shape & Reshape

arr1 = np.array([[1,2,3],[2,3,4]])
print(arr1.shape)

reshaped = arr1.reshape(3,2)
print(reshaped)

(2, 3)
[[1 2]
 [3 2]
 [3 4]]


In [16]:
#  Indexing and Slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:]) 

print(arr[::-1])

print(arr[:3])

[20 30 40 50]
[50 40 30 20 10]
[10 20 30]


In [20]:
# Arithmetic Operations

###  Element-wise addition, subtraction, multiplication

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)
print(a**2)
print(a*b)
print(a-b)

[5 7 9]
[1 4 9]
[ 4 10 18]
[-3 -3 -3]


In [26]:
# Aggregation Functions

data = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(data))
print(np.mean(data))
print(np.min(data,axis=0))

21
3.5
[1 2 3]


In [27]:
# Transpose multiplication

a = np.array([[1, 2], [3, 4]])
print(a.T)  

[[1 3]
 [2 4]]


In [28]:
# Sorting

arr = np.array([4, 2, 1, 2, 4, 1])
print(np.sort(arr))

[1 1 2 2 4 4]


In [34]:
# Data Type Conversion

arr = np.array([1,2,3])
print("Before conversion ",arr.dtype)
arr = arr.astype('float32')
print("\nAfter conversion",arr.dtype)

Before conversion  int32

After conversion float32


In [35]:
# arange 

arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [37]:
arr = np.arange(5,10,3)
print(arr)

[5 8]


In [38]:
arr = np.arange(10, 0, -2)
print(arr)

[10  8  6  4  2]
