# Broadcasting rules

In [1]:
# Correct: 2D + 1D (Row-wise Broadcasting)

import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])


print(np.add(arr1,arr2))

[[2 4 6]
 [5 7 9]]


In [3]:
# Incorrect: Mismatched Inner Dimensions

a = np.array([[1,2,3],[2,4,6]])
b = np.array([1,2])

print(np.add(a,b))

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [4]:
# Correct: Scalar Broadcast

a = np.array([1,2,3])

result = a+5

print(result)

[6 7 8]


In [5]:
# Incorrect: Shape 

a = np.array([[1], [2], [3]])  
b = np.array([10, 20])        
print(a + b)

[[11 21]
 [12 22]
 [13 23]]
