# Common Types of universal functions in numpy

In [5]:
# Arithmetic Functions

import numpy as np 

a = np.array([1,2,3])
b = np.array([2,3,4,])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]


In [9]:
# Comparison Functions

a = np.array([1,4,1])
b = np.array([3,2,1])

print(np.greater(a,b))
print(np.equal(a,b))
print(np.less(a,b))

[False  True False]
[False False  True]
[ True False False]


In [11]:
# Rounding Functions

a = np.array([1.3,1.8,2.3,2.6,2.5])

print(np.ceil(a))
print(np.floor(a))
print(np.round(a))

[2. 2. 3. 3. 3.]
[1. 1. 2. 2. 2.]
[1. 2. 2. 3. 2.]


In [ ]:
# Aggregate ufuncs (with axis support)

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))



[5 7 9]
[ 6 15]


In [15]:
# Exponents and Logaarithms functions

a = np.array([1,2,3])
print(np.exp(a))          
print(np.log(a)) 

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
